language: python
python:
  - '3.5'
install:
  - 'pip install pipenv'
  - 'pipenv sync'

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_install:
  - export DJANGO_SETTINGS_MODULE=app.settings.travis

before_script:
  - psql -c "CREATE DATABASE anhd;" -U postgres

script:
  - python manage.py test
