language: python
python:
  - '3.5'
install:
  - 'pip install pipenv'
  - 'pipenv install'
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.6"

before_install:
  - export DJANGO_SETTINGS_MODULE=app.settings.travis
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1

before_script:
  - psql -c "CREATE DATABASE anhd;" -U postgres

script:
  - pipenv run python manage.py test
