language: python
python:
  - '3.5'
install:
  - 'pip install pipenv'
  - 'pipenv sync'

services: postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5432
before_install:
  - export DJANGO_SETTINGS_MODULE=app.settings.travis

before_script:
  - psql -c "CREATE DATABASE anhd;" -U postgres

script:
  - python manage.py test
