version: '2'
services:
  # https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose
  nginx:
    restart: always
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx:/app/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - static_volume:/static
    depends_on:
      - app
      - flower
    networks:
      - nginx_network
