version: "2"
services:
  app:
    env_file:
      - .env
  # https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose
  nginx:
    restart: always
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "8888:8888"
    volumes:
      - ./nginx:/app/nginx
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ../anhd-council-client/build_publish:/client
      - ../staging-anhd-council-client/build_publish:/staging-client
      - static_volume:/static
    depends_on:
      - app
      - flower
    networks:
      - nginx_network
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
