version: '2'
services:
  celery_default:
    env_file:
      - .env.dev
  celery_update:
    env_file:
      - .env.dev
  celerybeat:
    env_file:
      - .env.dev
  flower:
    ports:
      - '8888:8888'
  redis:
    ports:
      - '6378:6379'
  postgres:
    ports:
      - '5678:5432'
