version: "2"
services:
  app:
    stdin_open: true # for debugging w/ "docker attach app"
    tty: true # for debugging w/ "docker attach app"
    entrypoint: ["sh", "/app/docker-entrypoint.dev.sh"]
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development
  celery_default:
    env_file:
      - .env.dev
  celery_update:
    env_file:
      - .env.dev
  celerybeat:
    env_file:
      - .env.dev
  flower:
    ports:
      - "8888:8888"
  redis:
    ports:
      - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
  nginx:
  certbot:
