version: '2'
services:
  app:
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.development
  # celery_default:
    # entrypoint: "celery -A app worker -Q celery -l info -n celery_worker --concurrency=2 --pidfile=./celery/pids/default.pid --logfile=./celery/logs/default.log"
    # entrypoint: "celery multi start default update -A app -Q:default celery -Q:update update -l debug -c:default 2 -c:update 1 -n:default celery_worker -n:update update_worker --pidfile=./celery/pids/%n.pid --logfile=./celery/logs/%n.log"
  # celery_update:
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis
  #     - DJANGO_SETTINGS_MODULE=app.settings.development
  #   entrypoint: "celery -A app worker -Q update -l info -n update_worker --concurrency=1 --pidfile=./celery/pids/update.pid --logfile=./celery/logs/update.log"
    # entrypoint: "celery multi start update -A app -Q update -l info -c 1 -n update_worker --pidfile=./celery/pids/%n.pid --logfile=./celery/logs/%n.log"
