version: '2'
services:
  app:
    environment:
      - CELERY_BROKER_URL=redis://redis
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE=app.settings.development
      - DATABASE=postgres
  celery_default:
    environment:
      - CELERY_BROKER_URL=redis://redis
      - DJANGO_SETTINGS_MODULE=app.settings.development
    entrypoint: "celery -A app worker -Q celery -l info -n celery_worker --concurrency=2"
  celery_update:
    environment:
      - CELERY_BROKER_URL=redis://redis
      - DJANGO_SETTINGS_MODULE=app.settings.development
    entrypoint: "celery -A app worker -Q update -l info -n update_worker --concurrency=1"
  celerybeat:
    environment:
      - CELERY_BROKER_URL=redis://redis
      - DJANGO_SETTINGS_MODULE=app.settings.development
