version: '2'
services:
  # https://blog.devartis.com/django-development-with-docker-a-completed-development-cycle-7322ad8ba508
  app:
    restart: always
    build: .
    expose:
      - "8001"
    # command: python manage.py start
    container_name: "app"
    image: debian/latest
    environment:
        - ENVIRONMENT=production
        - DJANGO_SETTINGS_MODULE=app.settings.production
    links:
        - postgres:postgres
        - redis:redis
    depends_on:
        - postgres
        - redis
    ports:
      - '8001:8000'
    networks:
      - network1
    volumes:
      - ./:/app
    env_file: .env
    command: /usr/local/bin/gunicorn app.wsgi:application -w 2 -b :8000 --reload
  # celery:
  #   build: .
  #   command: celery -A app worker -l info
  #   environment:
  #       - DJANGO_SETTINGS_MODULE=app.settings.production
  #   networks:
  #     - network1
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./data:/data
  #   links:
  #       - postgres
  #       - redis
  # celery-beat:
  #   build: .
  #   command: celery -A app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   environment:
  #       - DJANGO_SETTINGS_MODULE=app.settings.production
  #   networks:
  #     - network1
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./data:/data
  #   links:
  #       - postgres
  #       - redis
  # https://www.distributedpython.com/2018/10/13/flower-docker/
  flower:
    image: mher/flower
    environment:
    - CELERY_BROKER_URL=redis://redis
    - FLOWER_PORT=8888
    ports:
      - 8888:8888
    networks:
      - network1
  redis:
    hostname: redis
    image: redis:alpine
    ports:
        - 6378:6379
    networks:
      - network1
  postgres:
    image: postgres:11
    # https://blog.2ndquadrant.com/basics-of-tuning-checkpoints/
    command: ["-c","huge_pages=try", "-c","effective_io_concurrency=1", "-c", "max_stack_depth=6MB", "-c", "maintenance_work_mem=512MB", "-c", "temp_buffers=128MB", "-c", "shared_buffers=1024MB", "-c", "checkpoint_timeout=30min", "-c", "checkpoint_completion_target=0.93", "-c", "max_wal_size=2048MB", "-c", "effective_cache_size=1024MB", "-c", "work_mem=512MB", "-c", "max_connections=200", "-c", "random_page_cost=1"]
    shm_size: '2GB'
    environment:
      - POSTGRES_DB=anhd
      - POSTGRES_USER=anhd
    ports:
      - 5678:5432
    networks:
      - network1
volumes:
  pg_vol1:
networks:
  network1:
